### ISSUE TITLE
Copying files stops after one group copies zero files.

### ISSUE THREAD

**Issue by reitzig** [reitzig/container-do#15]
```toml
# ContainerDo.toml

[container]
image = "ubuntu"
mounts = []

[[copy.setup]]
files = ["does_not_exist"]

[[copy.setup]]
files = ["does_exist"]
```

**Expected:** Container starts and file `does_exist` is present in container working directory.

**Actual:** Container starts and working directory is empty.
