### ISSUE TITLE
Single-file target path fails if it contains non-existing directories

### ISSUE THREAD

**Issue by reitzig** [reitzig/container-do#16]
```toml
# ContainerDo.toml
[container]
image = "ubuntu"
mounts = []

[[copy.setup]]
files = ["foo"]
to = "some/dir/foobar"
```

**Expected:** Container starts and file `some/dir/foobar` exists in container working directory.

**Actual:** Error because `some/dir` does not exist. (even after fixing #14 )
