### ISSUE TITLE
Determine container working directory correctly

### ISSUE THREAD

**Issue by reitzig** [reitzig/container-do#19]
**Given**

```Dockerfile
FROM alpine
WORKDIR /work
```

Build with Kaniko!

```toml
[container]
image = "custom-image"
```

**When:**

```
container-do pwd
```

**Expected:** Output `/work`
**Actual:** Output `/`
