### ISSUE TITLE
Add configuration for exposing ports

### ISSUE THREAD

**Issue by reitzig** [reitzig/container-do#3]
Expose ports from the tool container to the host, if the user so wishes.

_Use case:_ `container-do hugo server -D` backed by

```toml
[container]
image = "klakegg/hugo"

ports = [ "1313:1313" ]
```

_Test:_ nginx serving a single file; should be `curl`-able as long as the container is running.
