### ISSUE TITLE
Add option to build image

### ISSUE THREAD

**Issue by reitzig** [reitzig/container-do#8]
Sometimes you need a custom image.

When given a section like this:

```toml
[container.image.build]
name = "my-project-do"
fille = "Dockerfile"
context = "."
```

We should run something like

    docker build -t my-project-do -f Dockerfile .

and use the resulting image.

---

 - When should we rebuild?
 - Do we want to refactor and move image-related things to a section `[image]`?
